<?php
/**
 * Plugin Name:       Unofficial Abilities for {{TARGET_LABEL}}
 * Description:        MCP ability pack giving an agent full control of {{TARGET_LABEL}}, via the WP Abilities API + Agent Connector for WP.
 * Version:           0.0.0-dev
 * Requires Plugins:  agent-connector-for-wp
 * Requires PHP:      8.1
 * Author:            Generated by wp-mcp-generator
 * License:           GPL-2.0-or-later
 *
 * Agent Connector: Ability Pack
 * Agent Connector Target: {{TARGET_PLUGIN_FILE}}
 *
 * ---------------------------------------------------------------------------
 * RENAME this file and its parent folder to:
 *   unofficial-abilities-for-{{TARGET_SLUG}}/
 *   unofficial-abilities-for-{{TARGET_SLUG}}.php
 * and replace every {{PLACEHOLDER}} above. Leave Version as 0.0.0-dev — the
 * release CI stamps the real version into the built zip automatically; never
 * hand-edit it.
 *
 * You write NO permission / auth / domain-lock / audit code. Agent Connector
 * injects all of it for every ability registered here. Just describe abilities
 * and implement their behavior — optimized for the agent's convenience.
 * ---------------------------------------------------------------------------
 *
 * @package AcfwAbilityPack
 */

declare( strict_types=1 );

defined( 'ABSPATH' ) || exit;

define( 'ACFW_PACK_DIR', plugin_dir_path( __FILE__ ) );

// The lightweight registry that collects categories + ability definitions and
// registers them on the correct Abilities API hooks.
require_once ACFW_PACK_DIR . 'bootstrap.php';

// Adapter / reimplemented logic (load-modify-save helpers, schema, etc.).
// Pull in everything under src/ that you add.
foreach ( glob( ACFW_PACK_DIR . 'src/**/*.php' ) ?: array() as $__src ) {
	require_once $__src;
}

// Ability definitions. Each file calls ACFW_Pack::category(...) and
// ACFW_Pack::ability([...]) at require time; boot() registers them on the hooks.
foreach ( glob( ACFW_PACK_DIR . 'abilities/*.php' ) ?: array() as $__ab ) {
	require_once $__ab;
}

ACFW_Pack::boot();
