<?php
/**
 * Plugin Name:       Unofficial Abilities for WP-CLI
 * Description:        MCP ability pack that reimplements the WP-CLI command surface in native PHP, so an agent can manage WordPress (options, posts, users, terms, comments, plugins, themes, the database, cron, cache, and more) even on hosts where the `wp` binary, proc_open, or shell access is unavailable. A drop-in fallback for `agent-connector-for-wp/wp-cli`.
 * Version:           0.0.0-dev
 * Requires Plugins:  agent-connector-for-wp
 * Requires PHP:      8.1
 * Author:            Generated by wp-mcp-generator
 * License:           GPL-2.0-or-later
 *
 * Agent Connector: Ability Pack
 *
 * This pack has no single target plugin — it stands in for WP-CLI against
 * WordPress core itself. It activates whenever Agent Connector for WP is active.
 *
 * You write NO permission / auth / domain-lock / audit code. Agent Connector
 * injects all of it for every ability registered here.
 *
 * @package AcfwAbilityPackWpCli
 */

declare( strict_types=1 );

defined( 'ABSPATH' ) || exit;

define( 'ACFW_WPCLI_DIR', plugin_dir_path( __FILE__ ) );

// The lightweight registry that collects categories + ability definitions and
// registers them on the correct Abilities API hooks.
require_once ACFW_WPCLI_DIR . 'bootstrap.php';

// Shared helpers (output formatting, entity resolution, etc.).
foreach ( glob( ACFW_WPCLI_DIR . 'src/**/*.php' ) ?: array() as $__src ) {
	require_once $__src;
}

// Ability definitions. Each file calls ACFW_Pack::category(...) and
// ACFW_Pack::ability([...]) at require time; boot() registers them on the hooks.
foreach ( glob( ACFW_WPCLI_DIR . 'abilities/*.php' ) ?: array() as $__ab ) {
	require_once $__ab;
}

ACFW_Pack::boot();
