<?php
/**
 * Client for the published "ability pack" manifest.
 *
 * @package AgentConnectorForWp
 */

declare( strict_types=1 );

namespace AgentConnectorForWp\Services;

defined( 'ABSPATH' ) || exit;

/**
 * Fetches the published JSON manifest of companion "ability pack" plugins and
 * matches its entries against the WP plugins installed on this site.
 *
 * The manifest is a single GitHub release asset (`pack-index/index.json`) listing
 * every ability pack — each targets a specific host WP plugin (e.g. a pack "for
 * WooCommerce") and registers AI abilities through Agent Connector's API. This
 * client tells the admin which of *their* installed plugins have a pack available.
 *
 * Network access is best-effort and never fatal: the result is cached in a
 * transient, failures fall back to the last good copy, and malformed JSON or
 * entries are ignored defensively. See docs/directory-schema.md for the schema.
 */
final class PluginDirectory {

	/**
	 * Default ability-pack manifest URL — the stable `pack-index` release asset of
	 * the agent-connector-for-wp repo, regenerated by ability-packs-release.yml.
	 *
	 * We read this ONE file and cache it; nothing enumerates GitHub's releases list,
	 * so it scales to a very large number of packs. Override with the
	 * `agent_connector_for_wp_pack_index_url` filter. A failure is handled
	 * gracefully: the UI shows a clean "unavailable" state and falls back to the
	 * last cached copy, never a fatal.
	 */
	public const DEFAULT_PACK_INDEX_URL = 'https://github.com/soflyy/agent-connector-for-wp/releases/download/pack-index/index.json';

	/**
	 * Default Universal Abilities manifest URL — the stable
	 * `universal-abilities-index` release asset, refreshed by
	 * default-abilities-release.yml on every UAP release. A one-object JSON
	 * ({slug, version, download_url, …}) pointing at the latest *versioned* zip.
	 *
	 * Kept as its own manifest (not merged into pack-index) so the two release
	 * workflows never contend over a single asset. Override with the
	 * `agent_connector_for_wp_universal_abilities_index_url` filter.
	 */
	public const DEFAULT_UNIVERSAL_ABILITIES_INDEX_URL = 'https://github.com/soflyy/agent-connector-for-wp/releases/download/universal-abilities-index/index.json';

	/**
	 * Transient holding the last successfully fetched + normalized manifest.
	 *
	 * @var array<string,mixed>|false
	 */
	public const CACHE_KEY = 'agent_connector_for_wp_directory_cache';

	/**
	 * Transient holding the last good Universal Abilities manifest entry.
	 */
	public const UNIVERSAL_ABILITIES_CACHE_KEY = 'agent_connector_for_wp_uap_index_cache';

	/**
	 * Failure-backoff markers. When a fetch fails and nothing is cached, we set a
	 * short-lived marker so repeated calls in the same window skip the network
	 * instead of each eating a timeout ("negative caching"). A forced refresh
	 * (an explicit WP "Check Again") ignores the marker and retries.
	 */
	public const CACHE_FAIL_KEY               = 'agent_connector_for_wp_directory_fail';
	public const UNIVERSAL_ABILITIES_FAIL_KEY = 'agent_connector_for_wp_uap_index_fail';

	/**
	 * How long to suppress refetching after a failure, in seconds.
	 */
	private const FAIL_BACKOFF = 10 * MINUTE_IN_SECONDS;

	/**
	 * Transient lifetime: 12 hours.
	 */
	public const CACHE_TTL = 12 * HOUR_IN_SECONDS;

	/**
	 * Default network timeout for the manifest fetch, in seconds. Kept short so a
	 * slow or unreachable host never stalls an admin page render for long.
	 * Override with the `agent_connector_for_wp_manifest_timeout` filter.
	 */
	private const HTTP_TIMEOUT = 5;

	/**
	 * The manifest fetch timeout after the override filter, floored at 1s so it
	 * can never be set to a blocking/never value.
	 */
	private static function http_timeout(): int {
		$timeout = (int) apply_filters( 'agent_connector_for_wp_manifest_timeout', self::HTTP_TIMEOUT );

		return max( 1, $timeout );
	}

	/**
	 * The ability-pack manifest URL, after the override filter.
	 */
	public static function pack_index_url(): string {
		/**
		 * Filters the URL of the ability-pack manifest (pack-index).
		 *
		 * @param string $url Default manifest URL.
		 */
		return (string) apply_filters( 'agent_connector_for_wp_pack_index_url', self::DEFAULT_PACK_INDEX_URL );
	}

	/**
	 * Return the cached payload, or null when nothing usable has been cached yet.
	 *
	 * @return array{entries:array<int,array<string,string>>}|null
	 */
	public static function cached(): ?array {
		$cached = get_transient( self::CACHE_KEY );

		return ( is_array( $cached ) && isset( $cached['entries'] ) && is_array( $cached['entries'] ) )
			? $cached
			: null;
	}

	/**
	 * Fetch the manifest, preferring the cache. On a cache miss it hits the network;
	 * on a network/parse failure it falls back to any stale cached copy.
	 *
	 * @param bool $force When true, bypass the cache and refetch from the network.
	 *
	 * @return array{
	 *     entries: array<int,array<string,string>>,
	 *     stale: bool,
	 *     error: string,
	 *     url: string
	 * }
	 */
	public static function get( bool $force = false ): array {
		$url = self::pack_index_url();

		if ( ! $force ) {
			$cached = self::cached();
			if ( null !== $cached ) {
				return array(
					'entries' => $cached['entries'],
					'stale'   => false,
					'error'   => '',
					'url'     => $url,
				);
			}

			// Nothing cached AND we recently failed to fetch: skip the network so
			// repeated background fires don't each eat a timeout. A forced check
			// bypasses this.
			if ( get_transient( self::CACHE_FAIL_KEY ) ) {
				return array(
					'entries' => array(),
					'stale'   => false,
					'error'   => __( 'The ability-pack list is currently unavailable.', 'agent-connector-for-wp' ),
					'url'     => $url,
				);
			}
		}

		$fetched = self::fetch( $url );

		if ( null !== $fetched ) {
			set_transient( self::CACHE_KEY, array( 'entries' => $fetched['entries'] ), self::CACHE_TTL );
			delete_transient( self::CACHE_FAIL_KEY );

			return array(
				'entries' => $fetched['entries'],
				'stale'   => false,
				'error'   => '',
				'url'     => $url,
			);
		}

		// Fetch failed — back off so we don't retry the network on every fire.
		set_transient( self::CACHE_FAIL_KEY, 1, self::FAIL_BACKOFF );

		// Network/parse failed — fall back to any (possibly stale) cached copy.
		$cached = self::cached();
		if ( null !== $cached ) {
			return array(
				'entries' => $cached['entries'],
				'stale'   => true,
				'error'   => __( 'Could not refresh the ability-pack list; showing the last cached copy.', 'agent-connector-for-wp' ),
				'url'     => $url,
			);
		}

		return array(
			'entries' => array(),
			'stale'   => false,
			'error'   => __( 'The ability-pack list is currently unavailable.', 'agent-connector-for-wp' ),
			'url'     => $url,
		);
	}

	/**
	 * Drop the cached manifests so the next read refetches.
	 */
	public static function clear_cache(): void {
		delete_transient( self::CACHE_KEY );
		delete_transient( self::UNIVERSAL_ABILITIES_CACHE_KEY );
		delete_transient( self::CACHE_FAIL_KEY );
		delete_transient( self::UNIVERSAL_ABILITIES_FAIL_KEY );
	}

	/**
	 * The Universal Abilities manifest URL, after the override filter.
	 */
	public static function universal_abilities_index_url(): string {
		/**
		 * Filters the URL of the Universal Abilities manifest.
		 *
		 * @param string $url Default manifest URL.
		 */
		return (string) apply_filters(
			'agent_connector_for_wp_universal_abilities_index_url',
			self::DEFAULT_UNIVERSAL_ABILITIES_INDEX_URL
		);
	}

	/**
	 * The latest published Universal Abilities release, as
	 * {slug, version, download_url, name, source_url}, or null when the manifest
	 * is unreachable and nothing usable is cached.
	 *
	 * Cached in its own transient with the same best-effort, never-fatal policy as
	 * the ability-pack manifest: a network/parse failure falls back to the last
	 * good copy.
	 *
	 * @param bool $force When true, bypass the cache and refetch from the network.
	 *
	 * @return array{slug:string,version:string,download_url:string,name:string,source_url:string}|null
	 */
	public static function universal_abilities_entry( bool $force = false ): ?array {
		if ( ! $force ) {
			$cached = get_transient( self::UNIVERSAL_ABILITIES_CACHE_KEY );
			if ( is_array( $cached ) ) {
				return $cached;
			}

			// Nothing cached AND we recently failed: skip the network. A forced
			// check bypasses this.
			if ( get_transient( self::UNIVERSAL_ABILITIES_FAIL_KEY ) ) {
				return null;
			}
		}

		$entry = self::normalize_universal_abilities_entry(
			self::remote_json( self::universal_abilities_index_url() )
		);

		if ( null !== $entry ) {
			set_transient( self::UNIVERSAL_ABILITIES_CACHE_KEY, $entry, self::CACHE_TTL );
			delete_transient( self::UNIVERSAL_ABILITIES_FAIL_KEY );
			return $entry;
		}

		// Fetch failed — back off, then fall back to any (possibly stale) cached copy.
		set_transient( self::UNIVERSAL_ABILITIES_FAIL_KEY, 1, self::FAIL_BACKOFF );
		$cached = get_transient( self::UNIVERSAL_ABILITIES_CACHE_KEY );
		return is_array( $cached ) ? $cached : null;
	}

	/**
	 * Validate + normalize the Universal Abilities manifest object, or null when
	 * it lacks the fields needed to offer an update (version + download URL).
	 *
	 * @param mixed $decoded Decoded JSON.
	 *
	 * @return array{slug:string,version:string,download_url:string,name:string,source_url:string}|null
	 */
	private static function normalize_universal_abilities_entry( $decoded ): ?array {
		if ( ! is_array( $decoded ) ) {
			return null;
		}

		$str = static function ( $value ): string {
			return is_string( $value ) ? trim( $value ) : '';
		};

		$version      = $str( $decoded['version'] ?? '' );
		$download_url = $str( $decoded['download_url'] ?? '' );

		if ( '' === $version || '' === $download_url ) {
			return null;
		}

		$slug = $str( $decoded['slug'] ?? '' );

		return array(
			'slug'         => '' !== $slug ? $slug : self::UNIVERSAL_ABILITIES_SLUG,
			'version'      => $version,
			'download_url' => $download_url,
			'name'         => $str( $decoded['name'] ?? '' ),
			'source_url'   => $str( $decoded['source_url'] ?? '' ),
		);
	}

	/**
	 * Fetch + decode + normalize the ability-pack manifest from the network.
	 *
	 * @param string $url Manifest URL.
	 *
	 * @return array{entries:array<int,array<string,string>>}|null Normalized entries, or null on any failure.
	 */
	private static function fetch( string $url ): ?array {
		$decoded = self::remote_json( $url );

		return null === $decoded ? null : self::normalize( $decoded );
	}

	/**
	 * GET a URL and decode it as JSON, or null on any network / HTTP / parse
	 * failure. Shared by the ability-pack manifest and the Universal Abilities
	 * manifest fetchers.
	 *
	 * @param string $url URL to fetch.
	 *
	 * @return mixed Decoded JSON (array/scalar) on success, or null on failure.
	 */
	private static function remote_json( string $url ) {
		if ( '' === $url || ! function_exists( 'wp_remote_get' ) ) {
			return null;
		}

		$response = wp_remote_get(
			$url,
			array(
				'timeout'    => self::http_timeout(),
				'user-agent' => 'AgentConnectorForWp/' . ( defined( 'AGENT_CONNECTOR_FOR_WP_VERSION' ) ? AGENT_CONNECTOR_FOR_WP_VERSION : 'dev' ),
				'headers'    => array( 'Accept' => 'application/json' ),
			)
		);

		if ( $response instanceof \WP_Error ) {
			return null;
		}

		if ( 200 !== (int) wp_remote_retrieve_response_code( $response ) ) {
			return null;
		}

		$body = wp_remote_retrieve_body( $response );
		if ( '' === $body ) {
			return null;
		}

		$decoded = json_decode( $body, true );
		if ( JSON_ERROR_NONE !== json_last_error() ) {
			return null;
		}

		return $decoded;
	}

	/**
	 * Normalize a decoded manifest into a clean list of entries.
	 *
	 * Accepts either a top-level array of entries, or an object with an `entries`
	 * key holding that array. Malformed entries are dropped.
	 *
	 * @param mixed $decoded Decoded JSON.
	 *
	 * @return array{entries:array<int,array<string,string>>}
	 */
	private static function normalize( $decoded ): array {
		$raw_entries = array();

		if ( is_array( $decoded ) && isset( $decoded['entries'] ) && is_array( $decoded['entries'] ) ) {
			$raw_entries = $decoded['entries'];
		} elseif ( is_array( $decoded ) ) {
			$raw_entries = $decoded;
		}

		$entries = array();
		foreach ( $raw_entries as $item ) {
			$entry = self::normalize_entry( $item );
			if ( null !== $entry ) {
				$entries[] = $entry;
			}
		}

		return array( 'entries' => $entries );
	}

	/**
	 * Validate + normalize a single manifest entry, or null if it is unusable.
	 *
	 * Required: target_plugin, ability_pack_name. Everything else is optional and
	 * defaulted to an empty string. `target_plugin` is the WP plugin the pack
	 * extends — the same value a pack declares in its `Agent Connector Target:`
	 * header.
	 *
	 * @param mixed $item Raw entry.
	 *
	 * @return array<string,string>|null
	 */
	private static function normalize_entry( $item ): ?array {
		if ( ! is_array( $item ) ) {
			return null;
		}

		$str = static function ( $value ): string {
			return is_string( $value ) ? trim( $value ) : '';
		};

		$target = $str( $item['target_plugin'] ?? '' );
		// Prefer ability_pack_name; fall back to the generic `name` field.
		$pack_name = $str( $item['ability_pack_name'] ?? '' );
		if ( '' === $pack_name ) {
			$pack_name = $str( $item['name'] ?? '' );
		}

		if ( '' === $target || '' === $pack_name ) {
			return null;
		}

		return array(
			'target_plugin'      => $target,
			'target_plugin_name' => $str( $item['target_plugin_name'] ?? '' ),
			'ability_pack_slug' => $str( $item['ability_pack_slug'] ?? '' ),
			'ability_pack_name' => $pack_name,
			'source_url'        => $str( $item['source_url'] ?? '' ),
			'description'       => $str( $item['description'] ?? '' ),
			'version'           => $str( $item['version'] ?? '' ),
			'download_url'      => $str( $item['download_url'] ?? '' ),
		);
	}

	/**
	 * Match manifest entries against the plugins installed on this site.
	 *
	 * @param array<int,array<string,string>> $entries Normalized manifest entries.
	 *
	 * @return array<int,array<string,mixed>> One row per match, each with the
	 *     entry plus target_plugin_file / target_plugin_name / target_active and
	 *     pack_installed / pack_active booleans.
	 */
	public static function match_installed( array $entries ): array {
		$installed = self::installed_plugins();

		$matches = array();
		foreach ( $entries as $entry ) {
			$target_key = self::find_installed_key( $entry['target_plugin'], $installed );
			if ( null === $target_key ) {
				continue;
			}

			$pack_key = '' !== $entry['ability_pack_slug']
				? self::find_installed_key( $entry['ability_pack_slug'], $installed )
				: null;

			$matches[] = array(
				'entry'              => $entry,
				'target_plugin_file' => $target_key,
				'target_plugin_name' => (string) ( $installed[ $target_key ]['Name'] ?? $entry['target_plugin_name'] ),
				'target_active'      => self::is_active( $target_key ),
				'pack_installed'    => null !== $pack_key,
				'pack_active'       => null !== $pack_key && self::is_active( $pack_key ),
			);
		}

		return $matches;
	}

	/**
	 * Every active installed plugin (minus the host and ability packs themselves),
	 * joined with its available ability pack when one exists. Drives the admin
	 * screen so plugins without a pack are still listed.
	 *
	 * Each row: plugin_file, plugin_name, plugin_active, has_pack, and — when
	 * has_pack — entry / pack_installed / pack_active.
	 *
	 * @return array{
	 *     rows: array<int,array<string,mixed>>,
	 *     stale: bool,
	 *     error: string,
	 *     url: string,
	 *     total: int
	 * }
	 */
	public static function installed_overview( bool $force = false ): array {
		$result = self::get( $force );

		$by_file = array();
		foreach ( self::match_installed( $result['entries'] ) as $match ) {
			$by_file[ $match['target_plugin_file'] ] = $match;
		}

		$rows = array();
		foreach ( self::installed_plugins() as $file => $data ) {
			if ( self::is_self_or_pack( $file, $data ) ) {
				continue;
			}
			if ( ! self::is_active( $file ) ) {
				continue; // Active plugins only.
			}

			if ( isset( $by_file[ $file ] ) ) {
				$row             = $by_file[ $file ];
				$row['has_pack'] = true;
			} else {
				$row = array(
					'has_pack'       => false,
					'entry'          => array(),
					'pack_installed' => false,
					'pack_active'    => false,
				);
			}

			$row['plugin_file']   = $file;
			$row['plugin_name']   = (string) ( $data['Name'] ?? $file );
			$row['plugin_active'] = true;

			$rows[] = $row;
		}

		// Rank: plugins with an available pack first, then the rest; alphabetical
		// within each group.
		usort(
			$rows,
			static function ( array $a, array $b ): int {
				$ra = empty( $a['has_pack'] ) ? 1 : 0;
				$rb = empty( $b['has_pack'] ) ? 1 : 0;
				if ( $ra !== $rb ) {
					return $ra <=> $rb;
				}
				return strcasecmp( (string) $a['plugin_name'], (string) $b['plugin_name'] );
			}
		);

		return array(
			'rows'  => $rows,
			'stale' => $result['stale'],
			'error' => $result['error'],
			'url'   => $result['url'],
			'total' => count( $result['entries'] ),
		);
	}

	/**
	 * Whether a plugin should be hidden from the overview: the host plugin itself,
	 * or an ability pack (carries the marker header, or follows the pack naming).
	 *
	 * @param string               $file Plugin file key.
	 * @param array<string,mixed>  $data get_plugins() entry.
	 */
	private static function is_self_or_pack( string $file, array $data ): bool {
		$slug = self::folder_slug( $file );

		if ( 'agent-connector-for-wp' === $slug ) {
			return true;
		}

		$marker = isset( $data['Agent Connector'] ) ? trim( (string) $data['Agent Connector'] ) : '';
		if ( '' !== $marker ) {
			return true;
		}

		return 0 === strpos( $slug, 'unofficial-abilities-for-' );
	}

	/**
	 * All installed plugins, keyed by plugin file (e.g. "woocommerce/woocommerce.php").
	 *
	 * @return array<string,array<string,mixed>>
	 */
	private static function installed_plugins(): array {
		if ( ! function_exists( 'get_plugins' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}

		return (array) get_plugins();
	}

	/**
	 * Resolve an ability-pack (or target) slug to its installed plugin file, or
	 * null when it isn't installed. Public so the admin install/activate flow and
	 * the pack updater can share the same tolerant matching.
	 */
	public static function installed_file_for_slug( string $slug ): ?string {
		return self::find_installed_key( $slug, self::installed_plugins() );
	}

	/**
	 * The Universal Abilities companion plugin's folder slug.
	 */
	public const UNIVERSAL_ABILITIES_SLUG = 'universal-abilities-plugin';

	/**
	 * Resolve the Universal Abilities companion plugin's installed file via the
	 * tolerant slug matcher (so it's found regardless of its main-file name), or
	 * null when it isn't installed.
	 */
	public static function universal_abilities_file(): ?string {
		return self::installed_file_for_slug( self::UNIVERSAL_ABILITIES_SLUG );
	}

	/**
	 * Whether the Universal Abilities companion plugin is installed AND active.
	 */
	public static function is_universal_abilities_active(): bool {
		$file = self::universal_abilities_file();

		return null !== $file && self::is_active( $file );
	}

	/**
	 * Resolve a manifest slug to an installed plugin file, tolerating slug format
	 * differences (full "folder/file.php" path vs bare folder slug).
	 *
	 * @param string                            $slug      Manifest-supplied slug.
	 * @param array<string,array<string,mixed>> $installed get_plugins() output.
	 *
	 * @return string|null The matching plugin file key, or null when not installed.
	 */
	private static function find_installed_key( string $slug, array $installed ): ?string {
		$slug = trim( $slug );
		if ( '' === $slug ) {
			return null;
		}

		// 1. Exact "folder/file.php" match.
		if ( isset( $installed[ $slug ] ) ) {
			return $slug;
		}

		// 2. Treat the supplied value as a folder slug and match on dirname,
		//    or on the file stem for single-file plugins ("hello.php").
		$needle = self::folder_slug( $slug );
		foreach ( array_keys( $installed ) as $file ) {
			if ( self::folder_slug( $file ) === $needle ) {
				return $file;
			}
		}

		return null;
	}

	/**
	 * Reduce a plugin file or slug to its comparable folder slug.
	 *
	 * "woocommerce/woocommerce.php" → "woocommerce"
	 * "woocommerce"                 → "woocommerce"
	 * "hello.php"                   → "hello"
	 */
	private static function folder_slug( string $value ): string {
		$value = trim( $value );
		if ( false !== strpos( $value, '/' ) ) {
			return dirname( $value );
		}

		// Single-file plugin or bare slug: strip a trailing ".php".
		return preg_replace( '/\.php$/', '', $value ) ?? $value;
	}

	/**
	 * Whether a plugin file is active (site-wide or, on multisite, network-active).
	 */
	private static function is_active( string $plugin_file ): bool {
		if ( ! function_exists( 'is_plugin_active' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}

		return is_plugin_active( $plugin_file );
	}
}
