import { NextRequest, NextResponse } from "next/server";

// Public, server-to-server endpoint hit by the Agent Connector for WP plugin.
// A site POSTs the plugins it has installed; we return the ability packs that
// target any of them, sourced from the single GitHub `pack-index` manifest.
//
// The manifest is the asset index.json of the agent-connector-for-wp repo's
// stable `pack-index` release (regenerated by ability-packs-release.yml). We read
// that ONE file and cache it — nothing enumerates GitHub's releases list, so this
// scales to a very large number of packs.

const DEFAULT_PACK_INDEX_URL =
  "https://github.com/soflyy/agent-connector-for-wp/releases/download/pack-index/index.json";

// How long (seconds) to cache the upstream manifest fetch at the edge.
const MANIFEST_REVALIDATE = 600;

interface ManifestEntry {
  ability_pack_slug: string;
  target_plugin: string;
  target_plugin_name?: string;
  name?: string;
  ability_pack_name?: string;
  version?: string;
  description?: string;
  download_url?: string;
  source_url?: string;
}

interface InstalledPlugin {
  slug?: string;
  file?: string;
  active?: boolean;
}

/** Reduce a plugin file or slug to its comparable folder slug.
 *  "woocommerce/woocommerce.php" -> "woocommerce"; "hello.php" -> "hello". */
function folderSlug(value: string): string {
  const v = (value || "").trim();
  if (!v) return "";
  if (v.includes("/")) return v.slice(0, v.indexOf("/"));
  return v.replace(/\.php$/, "");
}

async function fetchManifest(): Promise<ManifestEntry[] | null> {
  const url = process.env.PACK_INDEX_URL || DEFAULT_PACK_INDEX_URL;
  try {
    const res = await fetch(url, {
      headers: { Accept: "application/json" },
      next: { revalidate: MANIFEST_REVALIDATE },
    });
    if (!res.ok) return null;
    const data = await res.json();
    const entries = Array.isArray(data) ? data : data?.entries;
    return Array.isArray(entries) ? (entries as ManifestEntry[]) : [];
  } catch {
    return null;
  }
}

export async function POST(req: NextRequest) {
  let body: { plugins?: InstalledPlugin[] };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const plugins = Array.isArray(body?.plugins) ? body.plugins : null;
  if (!plugins) {
    return NextResponse.json({ error: "plugins[] is required" }, { status: 400 });
  }

  const manifest = await fetchManifest();
  if (manifest === null) {
    // Upstream manifest unavailable — signal failure so the caller keeps its
    // own last-good cache rather than treating "no packs" as authoritative.
    return NextResponse.json({ error: "Pack index unavailable" }, { status: 502 });
  }

  // Build the set of slugs the site has, so we can match either a full
  // "folder/file.php" target or a bare folder slug.
  const wanted = new Set<string>();
  for (const p of plugins) {
    if (p?.slug) wanted.add(folderSlug(p.slug));
    if (p?.file) wanted.add(folderSlug(p.file));
  }

  const entries = manifest.filter((e) => {
    const target = e?.target_plugin;
    if (!target) return false;
    return wanted.has(folderSlug(target)) || wanted.has(target);
  });

  return NextResponse.json({ entries });
}
