<?php
/**
 * Plugin Name:       Unofficial Abilities for Yoast SEO
 * Description:        MCP ability pack giving an agent full control of Yoast SEO (content SEO meta, search appearance, social, and general settings), via the WP Abilities API + Agent Connector for WP.
 * Version:           0.0.0-dev
 * Requires Plugins:  agent-connector-for-wp, wordpress-seo
 * Requires PHP:      8.1
 * Author:            Generated by wp-mcp-generator
 * License:           GPL-2.0-or-later
 *
 * Agent Connector: Ability Pack
 * Agent Connector Target: wordpress-seo/wp-seo.php
 *
 * You write NO permission / auth / domain-lock / audit code. Agent Connector
 * injects all of it for every ability registered here.
 *
 * @package AcfwAbilityPackYoast
 */

declare( strict_types=1 );

defined( 'ABSPATH' ) || exit;

define( 'ACFW_PACK_YOAST_DIR', plugin_dir_path( __FILE__ ) );

// The lightweight registry that collects categories + ability definitions and
// registers them on the correct Abilities API hooks.
require_once ACFW_PACK_YOAST_DIR . 'bootstrap.php';

// Adapter / reimplemented logic (load-modify-save helpers, field maps, schema).
foreach ( glob( ACFW_PACK_YOAST_DIR . 'src/**/*.php' ) ?: array() as $__src ) {
	require_once $__src;
}

// Ability definitions. Each file calls ACFW_Pack::category(...) and
// ACFW_Pack::ability([...]) at require time; boot() registers them on the hooks.
foreach ( glob( ACFW_PACK_YOAST_DIR . 'abilities/*.php' ) ?: array() as $__ab ) {
	require_once $__ab;
}

ACFW_Pack::boot();
