import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — Agent Ready Plugins Tracker",
  description:
    "All content on the Agent Ready Plugins Tracker is AI-generated. AI can make mistakes; verify before you rely on anything.",
};

const REPO = "https://github.com/soflyy/agent-connector-for-wp";

export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-12">
      <div className="mb-10">
        <Link href="/" className="text-sm text-wp-blue hover:underline">
          ← Back to directory
        </Link>
        <h1 className="mt-4 text-3xl font-bold tracking-tight text-slate-900">
          Disclaimer
        </h1>
        <p className="mt-3 text-lg text-slate-600">
          All content on this site is generated by AI. Treat it accordingly.
        </p>
      </div>

      <div className="mb-8 rounded-xl border border-amber-200 bg-amber-50 p-5 text-amber-900">
        <p className="leading-relaxed">
          <strong>AI can make mistakes.</strong> All content on this site is
          AI-generated. It may be incomplete, out of date, or simply wrong.
          Verify anything before you depend on it.
        </p>
      </div>

      <div className="space-y-8 text-slate-700">
        <section>
          <h2 className="mb-3 text-xl font-semibold text-slate-900">
            Use at your own risk
          </h2>
          <p className="leading-relaxed">
            Nothing here comes with any warranty — see the licenses in the{" "}
            <a href={REPO} className="text-wp-blue hover:underline">
              repository
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-slate-900">
            Found something wrong?
          </h2>
          <p className="leading-relaxed">
            Because this is AI-generated, errors are expected — and corrections
            are welcome. If a plugin's status or details are inaccurate, open an
            issue or PR on{" "}
            <a href={REPO} className="text-wp-blue hover:underline">
              GitHub
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
