import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — Agent Ready Plugins Tracker",
  description:
    "Agent Ready Plugins Tracker is largely AI-generated — the code, the ability packs, and the plugin information. AI can make mistakes; verify before you rely on anything.",
};

const REPO = "https://github.com/soflyy/agent-connector-for-wp";

export default function DisclaimerPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-12">
      <div className="mb-10">
        <Link href="/" className="text-sm text-wp-blue hover:underline">
          ← Back to directory
        </Link>
        <h1 className="mt-4 text-3xl font-bold tracking-tight text-slate-900">
          Disclaimer
        </h1>
        <p className="mt-3 text-lg text-slate-600">
          Almost everything here is generated by AI. Treat it accordingly.
        </p>
      </div>

      <div className="mb-8 rounded-xl border border-amber-200 bg-amber-50 p-5 text-amber-900">
        <p className="leading-relaxed">
          <strong>AI can make mistakes.</strong> The code, the ability packs, the
          site itself, and the information about each plugin are all
          AI-generated. They may be incomplete, out of date, or simply wrong.
          Verify anything before you depend on it.
        </p>
      </div>

      <div className="space-y-8 text-slate-700">
        <section>
          <h2 className="mb-3 text-xl font-semibold text-slate-900">
            What's AI-generated
          </h2>
          <ul className="space-y-3">
            <li className="flex gap-3">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-400" />
              <span>
                <strong>The ability packs.</strong> The unofficial MCP surfaces
                are produced automatically by the generator skill. They're
                verified during generation, but they are not written or audited
                by the plugin authors and can behave unexpectedly.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-400" />
              <span>
                <strong>This website and its code.</strong> The directory site
                and much of the surrounding tooling were generated by AI.
              </span>
            </li>
            <li className="flex gap-3">
              <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-slate-400" />
              <span>
                <strong>The plugin information.</strong> Descriptions, AI-readiness
                classifications, and other details about each plugin are
                AI-generated and may not reflect the current state of the plugin.
              </span>
            </li>
          </ul>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-slate-900">
            Use at your own risk
          </h2>
          <p className="leading-relaxed">
            The ability packs let AI agents take real actions in a WordPress
            install. Review what an ability does before running it, prefer a
            staging environment, and keep backups. Nothing here comes with any
            warranty — see the licenses in the{" "}
            <a href={REPO} className="text-wp-blue hover:underline">
              repository
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="mb-3 text-xl font-semibold text-slate-900">
            Found something wrong?
          </h2>
          <p className="leading-relaxed">
            Because this is AI-generated, errors are expected — and corrections
            are welcome. If a plugin's status or details are inaccurate, open an
            issue or PR on{" "}
            <a href={REPO} className="text-wp-blue hover:underline">
              GitHub
            </a>
            . See the{" "}
            <Link href="/contribute" className="text-wp-blue hover:underline">
              Contribute
            </Link>{" "}
            page for how to help.
          </p>
        </section>
      </div>
    </main>
  );
}
