// ─── MCP Bundle (.mcpb) builder ──────────────────────────────────────────────
//
// An MCP Bundle (https://github.com/modelcontextprotocol/mcpb) is a zip with a
// manifest.json and the server code. Hosts that support it (Claude Desktop
// first among them) install it in one click and run Node servers with their own
// bundled Node.js, so unlike the npx proxy path the operator needs no Node.js.
//
// The bundle ships a tiny dependency-free bridge (BRIDGE_SOURCE) instead of
// @automattic/mcp-wordpress-remote: packing that package and its dependencies
// into a zip in the browser isn't practical, and the MCP Adapter's Streamable
// HTTP transport is simple enough (plain JSON responses, Mcp-Session-Id) to
// relay directly.
//
// The connection details, application password included, are written straight
// into the manifest so installing is a single click with nothing to configure.
// The file is therefore a credential: the Connect page warns the operator not
// to share it, and changing the password means downloading a new file. It's
// built entirely client-side, so an existing password never leaves the
// browser.

import JSZip from 'jszip'

const MANIFEST_VERSION = '0.3'

// The stdio <-> Streamable HTTP bridge the host runs as server/index.js.
// CommonJS and Node >= 18 (global fetch) so it runs on any host's bundled Node.
const BRIDGE_SOURCE = `#!/usr/bin/env node
// stdio <-> Streamable HTTP bridge to a WordPress MCP Adapter endpoint,
// authenticated with a WordPress application password.
// Generated by Agent Connector for WP.
'use strict'

const readline = require('readline')

const ENDPOINT = process.env.WP_API_URL
const AUTH = 'Basic ' + Buffer.from(
  (process.env.WP_API_USERNAME || '') + ':' + String(process.env.WP_API_PASSWORD || '').replace(/\\s+/g, ''),
).toString('base64')

let sessionId = null
let initMessage = null

function log(...args) { console.error('[wordpress-mcpb]', ...args) }
function write(message) { process.stdout.write(JSON.stringify(message) + '\\n') }

// The adapter answers with plain JSON, but accept an SSE body too in case a
// future version streams: take the last data: payload that parses.
function parseBody(text, contentType) {
  if (!text) return null
  if (contentType.includes('text/event-stream')) {
    let last = null
    for (const line of text.split(/\\r?\\n/)) {
      if (!line.startsWith('data:')) continue
      try { last = JSON.parse(line.slice(5).trim()) } catch {}
    }
    return last
  }
  try { return JSON.parse(text) } catch { return null }
}

async function post(message) {
  const headers = {
    'Content-Type': 'application/json',
    Accept: 'application/json, text/event-stream',
    Authorization: AUTH,
  }
  if (sessionId) headers['Mcp-Session-Id'] = sessionId
  const res = await fetch(ENDPOINT, { method: 'POST', headers, body: JSON.stringify(message) })
  const sid = res.headers.get('mcp-session-id')
  if (sid) sessionId = sid
  const text = await res.text()
  return { status: res.status, text, body: parseBody(text, res.headers.get('content-type') || '') }
}

function isSessionError(body) {
  const err = body && !Array.isArray(body) && body.error
  return !!err && /session/i.test(String(err.message || ''))
}

// Sessions expire server-side; replay the handshake once and retry.
async function reinitialize() {
  sessionId = null
  await post(initMessage)
  await post({ jsonrpc: '2.0', method: 'notifications/initialized' })
}

async function handle(message) {
  const isRequest = message && !Array.isArray(message) && message.method !== undefined && message.id !== undefined
  if (isRequest && message.method === 'initialize') {
    initMessage = message
    sessionId = null
  }
  try {
    let res = await post(message)
    if (initMessage && message.method !== 'initialize' && isSessionError(res.body)) {
      log('session expired, reinitializing')
      await reinitialize()
      res = await post(message)
    }
    if (res.body && (Array.isArray(res.body) || res.body.jsonrpc)) {
      write(res.body)
    } else if (isRequest) {
      // A non-JSON-RPC failure (auth, REST routing, HTML error page…).
      const detail = (res.body && res.body.message) || res.text.slice(0, 300) || 'no response body'
      write({ jsonrpc: '2.0', id: message.id, error: { code: -32000, message: 'HTTP ' + res.status + ': ' + detail } })
    }
  } catch (e) {
    log(e)
    if (isRequest) write({ jsonrpc: '2.0', id: message.id, error: { code: -32000, message: 'Request to ' + ENDPOINT + ' failed: ' + e.message } })
  }
}

// Handle messages one at a time so the session from initialize is in place
// before anything that depends on it.
let queue = Promise.resolve()
const rl = readline.createInterface({ input: process.stdin })
rl.on('line', (line) => {
  if (!line.trim()) return
  let message
  try { message = JSON.parse(line) } catch {
    write({ jsonrpc: '2.0', id: null, error: { code: -32700, message: 'Parse error' } })
    return
  }
  queue = queue.then(() => handle(message))
})
rl.on('close', () => {
  queue.then(async () => {
    if (sessionId) {
      try {
        await fetch(ENDPOINT, { method: 'DELETE', headers: { Authorization: AUTH, 'Mcp-Session-Id': sessionId } })
      } catch {}
    }
    process.exit(0)
  })
})

if (!ENDPOINT) log('WP_API_URL is not set')
`

// The file name offered for download: the server name, which is already a
// filesystem-safe slug.
export function mcpbFileName(serverName) {
  return `${serverName}.mcpb`
}

export function buildManifest({ serverName, serverUrl, siteName, username, password }) {
  let host = serverUrl
  try { host = new URL(serverUrl).host } catch {}
  const label = siteName || host

  return {
    manifest_version: MANIFEST_VERSION,
    name: serverName,
    display_name: `${label} (WordPress)`,
    version: '1.0.0',
    description: `Gives the agent access to the WordPress site ${host} through Agent Connector for WP.`,
    author: { name: 'Soflyy' },
    server: {
      type: 'node',
      entry_point: 'server/index.js',
      mcp_config: {
        command: 'node',
        args: ['${__dirname}/server/index.js'],
        // Fixed values rather than user_config: a manifest with user_config
        // makes the host show a Configure form before the server starts, and
        // Claude Desktop won't save one whose values are all pre-filled
        // defaults, so the install gets stuck there.
        env: {
          WP_API_URL: serverUrl,
          WP_API_USERNAME: username,
          WP_API_PASSWORD: password,
        },
      },
    },
    icon: 'icon.png',
    compatibility: {
      platforms: ['darwin', 'win32', 'linux'],
      runtimes: { node: '>=18.0.0' },
    },
  }
}

const ICON_SIZE = 512

// The plugin's plug mark (lucide "plug", as in the admin header) on its indigo
// tile: the icon for sites without a Site Icon.
const FALLBACK_ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="${ICON_SIZE}" height="${ICON_SIZE}" viewBox="0 0 24 24">
<rect width="24" height="24" rx="5.5" fill="#4f46e5"/>
<g transform="translate(4.5 4.5) scale(0.625)" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
<path d="M12 22v-5"/><path d="M9 8V2"/><path d="M15 8V2"/><path d="M18 8v5a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V8Z"/>
</g></svg>`

function loadImage(src, crossOrigin) {
  return new Promise((resolve, reject) => {
    const img = new Image()
    if (crossOrigin) img.crossOrigin = 'anonymous'
    img.onload = () => resolve(img)
    img.onerror = () => reject(new Error('Could not load ' + src))
    img.src = src
  })
}

// Draws an image onto a square canvas and returns it as PNG, the format the
// manifest's icon field expects. Rejects if the canvas is tainted (a Site
// Icon on a CDN without CORS headers), so the caller can fall back.
async function toPng(src, crossOrigin) {
  const img = await loadImage(src, crossOrigin)
  const canvas = document.createElement('canvas')
  canvas.width = canvas.height = ICON_SIZE
  canvas.getContext('2d').drawImage(img, 0, 0, ICON_SIZE, ICON_SIZE)
  return new Promise((resolve, reject) => {
    try {
      canvas.toBlob((blob) => (blob ? resolve(blob) : reject(new Error('Empty icon'))), 'image/png')
    } catch (e) {
      reject(e)
    }
  })
}

// The site's own Site Icon, since the extension is named after the site;
// the plugin mark when there isn't one or it can't be read.
async function buildIcon(siteIcon) {
  if (siteIcon) {
    try { return await toPng(siteIcon, true) } catch {}
  }
  return toPng('data:image/svg+xml;charset=utf-8,' + encodeURIComponent(FALLBACK_ICON_SVG))
}

export async function buildMcpb(params) {
  const zip = new JSZip()
  zip.file('manifest.json', JSON.stringify(buildManifest(params), null, 2))
  zip.file('server/index.js', BRIDGE_SOURCE)
  zip.file('icon.png', await buildIcon(params.siteIcon))
  return zip.generateAsync({ type: 'blob', compression: 'DEFLATE' })
}

export async function downloadMcpb(params) {
  const blob = await buildMcpb(params)
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = mcpbFileName(params.serverName)
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
